# Generated by Django 4.0.5 on 2022-07-18 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_sale_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='tag',
            new_name='category',
        ),
    ]
