# Generated by Django 4.0.5 on 2022-07-19 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.FileField(upload_to='Home/Testimonials'),
        ),
    ]
