# Generated by Django 4.0.5 on 2022-07-13 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='featured_image',
            new_name='gray_image',
        ),
        migrations.AddField(
            model_name='brand',
            name='colored_image',
            field=models.FileField(default='Default Value', upload_to='brands'),
        ),
    ]
