# Generated by Django 4.0.5 on 2022-07-13 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_rename_featured_image_brand_gray_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='gray_image',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='colored_image',
        ),
    ]
