# Generated by Django 4.0.5 on 2022-07-19 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0003_rename_gray_image_brand_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.FileField(upload_to='Home/Brands'),
        ),
    ]
