# Generated by Django 4.0.6 on 2022-07-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0004_alter_brand_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.FileField(upload_to='home/brands'),
        ),
    ]
