# Generated by Django 4.0.5 on 2022-07-15 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_member',
            name='facebook',
            field=models.TextField(default='Not Available'),
        ),
        migrations.AddField(
            model_name='team_member',
            name='linkedIn',
            field=models.TextField(default='Not Available'),
        ),
        migrations.AddField(
            model_name='team_member',
            name='twitter',
            field=models.TextField(default='Not Available'),
        ),
    ]
