# Generated by Django 4.0.5 on 2022-07-19 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_members', '0004_alter_team_member_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_member',
            name='image',
            field=models.FileField(upload_to='About/Team Members'),
        ),
    ]
